sudo: required
dist: trusty

cache:
  directories:
    - ~/.wshash
  
language: node_js

node_js:
  - "6"

before_install:
  - sudo add-apt-repository -y ppa:wiseplat/wiseplat
  - sudo apt-get update
  - sudo apt-get install -y gwsh
  - mkdir -p ~/.wiseplat
  - mkdir -p ~/.wshash
  - gwsh makedag 0 ~/.wshash

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com

